### ISSUE TITLE
when I use uploadFile api,throw errors with panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xiaobeiy** [openimsdk/open-im-sdk-flutter#125]
**Describe the bug**
version: flutter-open-im-sdk 3.4.0+2 
when I call the api of "OpenIM.iMManager.uploadFile",it throws the error:

V/AudioManager( 7374): querySoundEffectsEnabled...
I/F-OpenIMSDK(flutter call native)( 7374): { class:imManager,  method:uploadFile }
I/GoLog   ( 7374): 2023-11-28 14:25:24.843      INFO    [PID:7374]      [open_im_sdk/util.go:104]       call function   {"operationID": "1701181524840", "in sdk args": ["{\"ManagerName\":\"imManager\",\"filePath\":\"\\/data\\/user\\/0\\/cn.net.shihong.rcb\\/files\\/note.png\",\"name\":\"note.png\",\"cause\":null,\"operationID\":\"1701181524840\",\"id\":\"2a833772-4bb3-4661-ab51-3799d210e970\",\"contentType\":null}",{"Bind_Num":63}]}
I/GoLog   ( 7374): 2023-11-28 14:25:24.844      INFO    [PID:7374]      [open_im_sdk/util.go:116]       input req       {"operationID": "1701181524840", "function name": "github.com/openimsdk/openim-sdk-core/v3/internal/file.(*File).UploadFile-fm", "args": ["{\"ManagerName\":\"imManager\",\"filePath\":\"\\/data\\/user\\/0\\/cn.net.shihong.rcb\\/files\\/note.png\",\"name\":\"note.png\",\"cause\":null,\"operationID\":\"1701181524840\",\"id\":\"2a833772-4bb3-4661-ab51-3799d210e970\",\"contentType\":null}",{"Bind_Num":63}]}
I/F-OpenIMSDK(native call flutter)( 7374): { method:uploadFileListener,  type:open }
I/F-OpenIMSDK(native call flutter)( 7374): { method:uploadFileListener,  type:partSize }
I/F-OpenIMSDK(native call flutter)( 7374): { method:uploadFileListener,  type:hashPartProgress }
I/F-OpenIMSDK(native call flutter)( 7374): { method:uploadFileListener,  type:hashPartComplete }
I/GoLog   ( 7374): 2023-11-28 14:25:24.859      DEBUG   [PID:7374]      [log/sql_logger.go:86]  sql exec detail {"operationID": "1701181524840", "gorm": "github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/pkg/db/upload_model.go:32", "elapsed time": "1.488021(ms)", "rows": 1, "sql": "SELECT * FROM `local_uploads` WHERE part_hash = \"9de9ca8a93298dda579c3b874cf1278b\" LIMIT 1"}
I/GoLog   ( 7374): 2023-11-28 14:25:24.871      DEBUG   [PID:7374]      [log/sql_logger.go:86]  sql exec detail {"operationID": "1701181524840", "gorm": "github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/pkg/db/upload_model.go:46", "elapsed time": "11.567188(ms)", "rows": 1, "sql": "DELETE FROM `local_uploads` WHERE part_hash = \"9de9ca8a93298dda579c3b874cf1278b\""}
I/GoLog   ( 7374): panic: runtime error: invalid memory address or nil pointer dereference
I/GoLog   ( 7374): goroutine 188 [running]:
I/GoLog   ( 7374): runtime/debug.Stack()
I/GoLog   ( 7374):      runtime/debug/stack.go:24 +0x68
I/GoLog   ( 7374): github.com/openimsdk/openim-sdk-core/v3/open_im_sdk.call_.func1()
I/GoLog   ( 7374):      github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/open_im_sdk/util.go:91 +0x40
I/GoLog   ( 7374): panic({0x7a996a4da0, 0x7a99c66e80})
I/GoLog   ( 7374):      runtime/panic.go:838 +0x204
I/GoLog   ( 7374): github.com/openimsdk/openim-sdk-core/v3/internal/file.(*File).getUpload(0x40004ae460, {0x7a997a4ce8, 0x4000500ed0}, 0x400059e800)
I/GoLog   ( 7374):      github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/internal/file/upload.go:444 +0x958
I/F-OpenIMSDK(native call flutter)( 7374): method: 【 uploadFile 】, onError: { code:10005, message:error *errors.errorString not implement CodeError: call panic: runtime error: invalid memory address or nil pointer dereference}
I/GoLog   ( 7374): github.com/openimsdk/openim-sdk-core/v3/internal/file.(*File).UploadFile(0x40004ae460, {0x7a997a4ce8, 0x4000500ed0}, 0x400008c690, {0x7ae30950d8, 0x40004f2054})
I/GoLog   ( 7374):      github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/internal/file/upload.go:147 +0x498
I/GoLog   ( 7374): reflect.Value.call({0x7a996a11a0?, 0x4000126000?, 0x400019e658?}, {0x7a98d0ef4d, 0x4}, {0x400008c640, 0x3, 0x7a98ee07bc?})
I/GoLog   ( 7374):      reflect/value.go:556 +0x5fc
I/GoLog   ( 7374): reflect.Value.Call({0x7a996a11a0?, 0x4000126000?, 0xe0?}, {0x400008c640, 0x3, 0x3})
I/GoLog   ( 7374):      reflect/value.go:339 +0x98
I/GoLog   ( 7374): github.com/openimsdk/openim-sdk-core/v3/open_im_sdk.call_({0x40004f2240, 0xd}, {0x7a996a11a0, 0x4000126000}, {0x4000430040?, 0x2, 0x2})
I/GoLog   ( 7374):      github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/open_im_sdk/util.go:159 +0xde4
I/GoLog   ( 7374): github.com/openimsdk/openim-sdk-core/v3/open_im_sdk.call.func1()
I/GoLog   ( 7374):      github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/open_im_sdk/util.go:204 +0x4c
I/GoLog   ( 7374): created by github.com/openimsdk/openim-sdk-core/v3/open_im_sdk.call
I/GoLog   ( 7374):      github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/open_im_sdk/util.go:203 +0x18c
I/flutter ( 7374): Error FROM OUT_SIDE FRAMEWORK
I/flutter ( 7374): --------------------------------
I/flutter ( 7374): Error :  PlatformException10(005, error *errors.errorString not implement CodeError: call panic: runtime error: invalid memory address or nil pointer dereference, null, null)   
I/flutter ( 7374): StackTrace :  #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
I/flutter ( 7374): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
I/flutter ( 7374): <asynchronous suspension>
I/flutter ( 7374): #2      InitImDataController.uploadSpecialImage (package:rcb/page/dapp/my/applets/init_im_data/init_im_data_controller.dart:205:20)
I/flutter ( 7374): <asynchronous suspension>
I/GoLog   ( 7374): 2023-11-28 14:25:33.822      INFO    [PID:7374]      [interaction/long_conn_mgr.go:309]      ping and getMaxSeq start        {"operationID": "1701181535038317679", "goroutine ID:": 33}
I/GoLog   ( 7374): 2023-11-28 14:25:33.852      INFO    [PID:7374]      [interaction/long_conn_mgr.go:430]      recv msg        {"operationID": "1701181535038317679", "errCode": 0, "errMsg": "", "reqIdentifier": 1001}
I/GoLog   ( 7374): 2023-11-28 14:25:33.852      INFO    [PID:7374]      [interaction/msg_sync.go:130]   recv max seqs from long conn mgr, start sync msgs       {"operationID": "1701181535038317679", "cmd": "maxSeq", "value": {"ConversationMaxSeqOnSvr":null}}
I/GoLog   ( 7374): 2023-11-28 14:25:33.853      DEBUG   [PID:7374]      [interaction/msg_sync.go:305]   noting conversation to sync     {"operationID": "1701181425627", "syncMsgNum": 10}

**How to reproduce**
just in flutter app,call the api OpenIM.iMManager.uploadFile，the file is from assets，such as：
String noteimg = "static/res/note.png";
List filedirList = noteimg.split("/");
File file = await RUtils.readAndWriteImage(imgName: filedirList[filedirList.length -1], imgPath: noteimg);
var result = await OpenIM.iMManager.uploadFile(
        id: Uuid().v4(),
        filePath: file.path, 
        fileName: filedirList[filedirList.length -1]
      );
then it will throws the error

**Version information**
- Device: HUAWEI P20
- OS: Android
- Package Version: flutter_openim_sdk 3.4.0+2
- Flutter Version: 3.16.1

**Comment by xiaobeiy** [comment]
The value of the "OPENIM_IP" variable in the official document is incorrect, it should only be IP, without port number and prefix http.
export OPENIM_IP="http://ip:10002" --> export OPENIM_IP="ip"
