### ISSUE TITLE
[BUG] 调用 `setConversationEx` 会报 type 'String' is not a subtype of type 'List<dynamic>' in type cast

### ISSUE THREAD

**Issue by cipchk** [openimsdk/open-im-sdk-flutter#138]
## 重现

```dark
OpenIM.iMManager.conversationManager.setConversationEx(
  cov.conversationID,
  ex: "test",
);
```

抛出：

```
I/flutter (17431): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (17431): │ type 'String' is not a subtype of type 'List<dynamic>' in type cast
I/flutter (17431): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (17431): │ #0   Utils.toList (package:flutter_openim_sdk/src/utils.dart:5:26)
I/flutter (17431): │ #1   ConversationManager.setConversationEx.<anonymous closure> (package:flutter_openim_sdk/src/manager/im_conversation_manager.dart:372:32)
I/flutter (17431): │ #2   _rootRunUnary (dart:async/zone.dart:1407:47)
I/flutter (17431): │ #3   _CustomZone.runUnary (dart:async/zone.dart:1308:19)
I/flutter (17431): │ #4   Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:847:45)
I/flutter (17431): │ #5   Future._propagateToListeners (dart:async/future_impl.dart:876:13)
I/flutter (17431): │ #6   Future._completeWithValue (dart:async/future_impl.dart:652:5)
I/flutter (17431): │ #7   <asynchronous suspension>
I/flutter (17431): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
```

**Comment by std-s** [comment]
Hi, we will fix it in the next version.

**Comment by pokid** [comment]
i met this problem too,may i ask when to publish the new version
