### ISSUE TITLE
拍摄发送图片  atal error: memory reservation exceeds address space limit

### ISSUE THREAD

**Issue by adger-me** [OpenIMSDK/Open-IM-SDK-Flutter#83]
IOS 设备

**Comment by adger-me** [comment]
`
/private/var/mobile/Containers/Data/Application/C5011748-3F98-48AA-8CAB-24B617028D98/tmp/flutter-images/58005e7e27b51eede23b44c2ecf2374f_exif.jpg]
runtime: memory allocated by OS [0x2ab800000, 0x2adc00000) not in usable address space: base outside usable address space
fatal error: memory reservation exceeds address space limit


runtime stack:
runtime.throw({0x10641a408, 0x2e})
	runtime/panic.go:1198 +0x54
runtime.(*mheap).sysAlloc(0x106fb61a0, 0x2400000)
	runtime/malloc.go:721 +0x604
runtime.(*mheap).grow(0x106fb61a0, 0x1172)
	runtime/mheap.go:1347 +0x7c
runtime.(*mheap).allocSpan(0x106fb61a0, 0x1172, 0x0, 0x1)
	runtime/mheap.go:1179 +0x188
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:913 +0x88
runtime.systemstack()
	runtime/asm_arm64.s:230 +0x6c


goroutine 17 [running, locked to thread]:
runtime.systemstack_switch()
	runtime/asm_arm64.s:187 +0x8 fp=0x13072acf0 sp=0x13072ace0 pc=0x1057eb0a8
runtime.(*mheap).alloc(0x106fb61a0, 0x1172, 0x1, 0x0)
	runtime/mheap.go:907 +0x64 fp=0x13072ad40 sp=0x13072acf0 pc=0x1057ace54
runtime.(*mcache).allocLarge(0x1083f8108, 0x22e2400, 0x0, 0x1)
	runtime/mcache.go:227 +0x8c fp=0x13072ada0 sp=0x13072ad40 pc=0x10579c54c
runtime.mallocgc(0x22e2400, 0x1065da400, 0x1)
	runtime/malloc.go:1082 +0x5ac fp=0x13072ae30 sp=0x13072ada0 pc=0x105792a7c
runtime.makeslice(0x1065da400, 0x22e2400, 0x22e2400)
	runtime/slice.go:98 +0x90 fp=0x13072ae60 sp=0x13072ae30 pc=0x1057d39a0
image.NewYCbCr({{0x0, 0x0}, {0xfc0, 0xbd0}}, 0x0)
	image/ycbcr.go:189 +0x138 fp=0x13072af00 sp=0x13072ae60 pc=0x105d308d8
image/jpeg.(*decoder).makeImg(0x156c0b500, 0x1f8, 0x17a)
	image/jpeg/scan.go:40 +0x108 fp=0x13072af60 sp=0x13072af00 pc=0x105d39068
image/jpeg.(*decoder).processSOS(0x156c0b500, 0xa)
	image/jpeg/scan.go:150 +0x40c fp=0x13072b1a0 sp=0x13072af60 pc=0x105d396ec
image/jpeg.(*decoder).decode(0x156c0b500, {0x1066e0d40, 0x1307184e0}, 0x0)
	image/jpeg/reader.go:627 +0x200 fp=0x13072b1f0 sp=0x13072b1a0 pc=0x105d37fc0
image/jpeg.Decode({0x1066e0d40, 0x1307184e0})
	image/jpeg/reader.go:776 +0x4c fp=0x13072b240 sp=0x13072b1f0 pc=0x105d38c9c
image.Decode({0x1066e26a0, 0x13051a818})
	image/format.go:93 +0x1c8 fp=0x13072b330 sp=0x13072b240 pc=0x105d2a358
open_im_sdk/internal/conversation_msg.getImageInfo({0x13046c1e0, 0x91})
	open_im_sdk@v0.0.0-00010101000000-000000000000/internal/conversation_msg/open_im_sdk_conversation_msg.go:1475 +0x90 fp=0x13072b3e0 sp=0x13072b330 pc=0x105da2df0
open_im_sdk/internal/conversation_msg.(*Conversation).CreateImageMessageFromFullPath(0x1302c5380, {0x13046c1e0, 0x91}, {0x130693360, 0xd})
	open_im_sdk@v0.0.0-00010101000000-000000000000/internal/conversation_msg/open_im_sdk_conversation_msg.go:413 +0x198 fp=0x13072bd70 sp=0x13072b3e0 pc=0x105d96308
open_im_sdk/open_im_sdk.CreateImageMessageFromFullPath(...)
	open_im_sdk@v0.0.0-00010101000000-000000000000/open_im_sdk/open_im_sdk_interface.go:670
main.proxyopen_im_sdk__CreateImageMessageFromFullPath({0x281854110, 0xd, {0x0, 0x0, 0x0, 0x0}}, {0x282b63de0, 0x91, {0x0, 0x0, ...}})
	gobind/gobind/go_open_im_sdkmain.go:348 +0x94 fp=0x13072bde0 sp=0x13072bd70 pc=0x105dd4ef4
_cgoexp_183178bade1c_proxyopen_im_sdk__CreateImageMessageFromFullPath(0x16bbd8c80)
	_cgo_gotypes.go:1559 +0x68 fp=0x13072be60 sp=0x13072bde0 pc=0x105dde718
runtime.cgocallbackg1(0x105dde6b0, 0x16bbd8c80, 0x0)
	runtime/cgocall.go:306 +0x1f4 fp=0x13072bf30 sp=0x13072be60 pc=0x1057898c4
runtime.cgocallbackg(0x105dde6b0, 0x16bbd8c80, 0x0)
	runtime/cgocall.go:232 +0xe0 fp=0x13072bfb0 sp=0x13072bf30 pc=0x105789640
runtime.cgocallback(0x0, 0x0, 0x0)
	runtime/asm_arm64.s:1055 +0x98 fp=0x13072bfe0 sp=0x13072bfb0 pc=0x1057ed4d8
runtime.goexit()
	runtime/asm_arm64.s:1133 +0x4 fp=0x13072bfe0 sp=0x13072bfe0 pc=0x1057ed5b4


goroutine 51 [syscall, 2 minutes]:
os/signal.signal_recv()
	runtime/sigqueue.go:166 +0x34
os/signal.loop()
	os/signal/signal_unix.go:24 +0x20
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x38


goroutine 122 [chan receive]:
open_im_sdk/pkg/common.DoListener({0x1066ecee8, 0x1302c5380})
	open_im_sdk@v0.0.0-00010101000000-000000000000/pkg/common/trigger_channel.go:113 +0x11c
created by open_im_sdk/internal/login.(*LoginMgr).login
	open_im_sdk@v0.0.0-00010101000000-000000000000/internal/login/init_login.go:231 +0x15dc


goroutine 56 [select, 2 minutes]:
database/sql.(*DB).connectionOpener(0x1301af860, {0x1066f29d8, 0x130386d00})
	database/sql/sql.go:1196 +0x94
created by database/sql.OpenDB
	database/sql/sql.go:794 +0x158


goroutine 38 [IO wait]:
internal/poll.runtime_pollWait(0x10a52ef58, 0x72)
	runtime/netpoll.go:229 +0xa4
internal/poll.(*pollDesc).wait(0x13040a418, 0x72, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x38
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x13040a400, {0x13055d000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x1dc
net.(*netFD).Read(0x13040a400, {0x13055d000, 0x1000, 0x1000})
	net/fd_posix.go:56 +0x44
net.(*conn).Read(0x1306a2450, {0x13055d000, 0x1000, 0x1000})
	net/net.go:183 +0x4c
bufio.(*Reader).fill(0x13040ea80)
	bufio/bufio.go:101 +0x10c
bufio.(*Reader).Peek(0x13040ea80, 0x2)
	bufio/bufio.go:139 +0x6c
github.com/gorilla/websocket.(*Conn).read(0x13001c580, 0x2)
	github.com/gorilla/websocket@v1.4.2/conn.go:370 +0x34
github.com/gorilla/websocket.(*Conn).advanceFrame(0x13001c580)
	github.com/gorilla/websocket@v1.4.2/conn.go:798 +0x90
github.com/gorilla/websocket.(*Conn).NextReader(0x13001c580)
	github.com/gorilla/websocket@v1.4.2/conn.go:980 +0xb4
github.com/gorilla/websocket.(*Conn).ReadMessage(0x13001c580)
	github.com/gorilla/websocket@v1.4.2/conn.go:1064 +0x28
open_im_sdk/internal/interaction.(*Ws).ReadData(0x13027a780)
	open_im_sdk@v0.0.0-00010101000000-000000000000/internal/interaction/ws.go:196 +0x234
created by open_im_sdk/internal/interaction.NewWs
	open_im_sdk@v0.0.0-00010101000000-000000000000/internal/interaction/ws.go:30 +0xd0


goroutine 67 [chan receive]:
open_im_sdk/pkg/common.DoListener({0x1066ecf10, 0x1300a9780})
	open_im_sdk@v0.0.0-00010101000000-000000000000/pkg/common/trigger_channel.go:113 +0x11c
created by open_im_sdk/internal/interaction.NewMsgSync
	open_im_sdk@v0.0.0-00010101000000-000000000000/internal/interaction/msg_sync.go:99 +0x108


goroutine 68 [select]:
open_im_sdk/internal/interaction.(*Heartbeat).Run(0x13057a0c0)
	open_im_sdk@v0.0.0-00010101000000-000000000000/internal/interaction/heartbeat.go:95 +0xd8
created by open_im_sdk/internal/interaction.NewHeartbeat
	open_im_sdk@v0.0.0-00010101000000-000000000000/internal/interaction/heartbeat.go:37 +0x12c


goroutine 159 [select]:
net/http.(*persistConn).writeLoop(0x1303de000)
	net/http/transport.go:2386 +0xac
created by net/http.(*Transport).dialConn
	net/http/transport.go:1748 +0x18a8


goroutine 130 [runnable]:
syscall.syscall(0x1058009a0, 0x5c, 0x130738000, 0x8000)
	runtime/sys_darwin.go:22 +0x1c
syscall.write(0x5c, {0x130738000, 0x8000, 0x8000})
	syscall/zsyscall_darwin_arm64.go:1635 +0x5c
syscall.Write(...)
	syscall/syscall_unix.go:214
internal/poll.ignoringEINTRIO(...)
	internal/poll/fd_unix.go:582
internal/poll.(*FD).Write(0x130619440, {0x130738000, 0x8000, 0x8000})
	internal/poll/fd_unix.go:275 +0x2b0
os.(*File).write(...)
	os/file_posix.go:49
os.(*File).Write(0x1306a3680, {0x130738000, 0x8000, 0x8000})
	os/file.go:176 +0x74
io.copyBuffer({0x1066e3880, 0x1303d8590}, {0x1066e26a0, 0x1306a3678}, {0x0, 0x0, 0x0})
	io/io.go:425 +0x224
io.Copy(...)
	io/io.go:382
os.genericReadFrom(0x1306a3680, {0x1066e26a0, 0x1306a3678})
	os/file.go:162 +0x78
os.(*File).ReadFrom(0x1306a3680, {0x1066e26a0, 0x1306a3678})
	os/file.go:156 +0x74
io.copyBuffer({0x1066e26c0, 0x1306a3680}, {0x1066e26a0, 0x1306a3678}, {0x0, 0x0, 0x0})
	io/io.go:409 +0x124
io.Copy(...)
	io/io.go:382
open_im_sdk/pkg/utils.CopyFile({0x13046c1e0, 0x91}, {0x13028b300, 0x7b})
	open_im_sdk@v0.0.0-00010101000000-000000000000/pkg/utils/file.go:27 +0x108
open_im_sdk/internal/conversation_msg.(*Conversation).CreateImageMessageFromFullPath.func1({0x13046c1e0, 0x91}, 0x1302c5380, 0x130693370)
	open_im_sdk@v0.0.0-00010101000000-000000000000/internal/conversation_msg/open_im_sdk_conversation_msg.go:401 +0x70
created by open_im_sdk/internal/conversation_msg.(*Conversation).CreateImageMessageFromFullPath
	open_im_sdk@v0.0.0-00010101000000-000000000000/internal/conversation_msg/open_im_sdk_conversation_msg.go:399 +0x88


goroutine 158 [IO wait]:
internal/poll.runtime_pollWait(0x10a52f040, 0x72)
	runtime/netpoll.go:229 +0xa4
internal/poll.(*pollDesc).wait(0x13059bd98, 0x72, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x38
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x13059bd80, {0x13022d000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x1dc
net.(*netFD).Read(0x13059bd80, {0x13022d000, 0x1000, 0x1000})
	net/fd_posix.go:56 +0x44
net.(*conn).Read(0x1306a2670, {0x13022d000, 0x1000, 0x1000})
	net/net.go:183 +0x4c
net/http.(*persistConn).Read(0x1303de000, {0x13022d000, 0x1000, 0x1000})
	net/http/transport.go:1926 +0x64
bufio.(*Reader).fill(0x130456900)
	bufio/bufio.go:101 +0x10c
bufio.(*Reader).Peek(0x130456900, 0x1)
	bufio/bufio.go:139 +0x6c
net/http.(*persistConn).readLoop(0x1303de000)
	net/http/transport.go:2087 +0x15c
created by net/http.(*Transport).dialConn
	net/http/transport.go:1747 +0x1888
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001bb010bbc libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1bb010bbc <+8>:  b.lo   0x1bb010bd8               ; <+36>
    0x1bb010bc0 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1bb010bc4 <+16>: mov    x29, sp
    0x1bb010bc8 <+20>: bl     0x1bb00c60c               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.
`
